name: journal_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

# This is the section you were missing
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # The packages you need
  cupertino_icons: ^1.0.8
  go_router: ^13.0.0
  intl: ^0.19.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true